export const carBrands: Record<string, string[]> = {
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'RS3', 'RS5', 'RS6', 'e-tron'],
  'BMW': ['Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'Série 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'M3', 'M4', 'M5', 'i4', 'iX'],
  'Citroën': ['C1', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C5 Aircross', 'Berlingo', 'ë-C4'],
  'Dacia': ['Sandero', 'Duster', 'Jogger', 'Spring', 'Logan'],
  'Fiat': ['500', '500X', 'Panda', 'Tipo', 'Punto', '500e'],
  'Ford': ['Fiesta', 'Focus', 'Puma', 'Kuga', 'Mustang', 'Ranger', 'Mondeo', 'Explorer', 'Mustang Mach-E'],
  'Honda': ['Civic', 'Jazz', 'HR-V', 'CR-V', 'ZR-V', 'e:Ny1', 'Honda e'],
  'Hyundai': ['i10', 'i20', 'i30', 'Tucson', 'Kona', 'Santa Fe', 'IONIQ 5', 'IONIQ 6', 'Bayon'],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Avenger'],
  'Kia': ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Sorento', 'Niro', 'EV6', 'EV9', 'Stonic'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar'],
  'Mazda': ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-30', 'CX-60', 'MX-5', 'MX-30'],
  'Mercedes-Benz': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'Classe S', 'CLA', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'AMG GT', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS'],
  'Mini': ['Cooper', 'Countryman', 'Clubman', 'Cooper SE'],
  'Mitsubishi': ['Space Star', 'ASX', 'Eclipse Cross', 'Outlander'],
  'Nissan': ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Leaf', 'Ariya', 'GT-R', 'Navara'],
  'Opel': ['Corsa', 'Astra', 'Mokka', 'Crossland', 'Grandland', 'Combo'],
  'Peugeot': ['208', '308', '2008', '3008', '5008', '508', 'Partner', 'e-208', 'e-2008'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', '718 Boxster', '718 Cayman'],
  'Renault': ['Clio', 'Captur', 'Mégane', 'Kadjar', 'Arkana', 'Austral', 'Scenic', 'ZOE', 'Megane E-Tech'],
  'Seat': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
  'Škoda': ['Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq'],
  'Smart': ['Fortwo', 'Forfour', '#1'],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'],
  'Toyota': ['Yaris', 'Yaris Cross', 'Corolla', 'C-HR', 'RAV4', 'Camry', 'Land Cruiser', 'Hilux', 'GR86', 'Supra', 'bZ4X'],
  'Volkswagen': ['Polo', 'Golf', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'Passat', 'Arteon', 'ID.3', 'ID.4', 'ID.5', 'ID.7', 'ID. Buzz'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90', 'C40 Recharge', 'EX30', 'EX90'],
};

export const carColors = [
  { label: 'Preto', value: 'black', hex: '#1a1a1a' },
  { label: 'Branco', value: 'white', hex: '#f5f5f5' },
  { label: 'Prata', value: 'silver metallic', hex: '#c0c0c0' },
  { label: 'Cinzento', value: 'dark gray metallic', hex: '#6b6b6b' },
  { label: 'Azul', value: 'deep blue metallic', hex: '#1e3a5f' },
  { label: 'Vermelho', value: 'red', hex: '#c41e3a' },
  { label: 'Verde', value: 'dark green metallic', hex: '#2d5a27' },
  { label: 'Amarelo', value: 'bright yellow', hex: '#ffd700' },
  { label: 'Laranja', value: 'orange', hex: '#e65100' },
  { label: 'Bordeaux', value: 'burgundy metallic', hex: '#722f37' },
  { label: 'Azul Claro', value: 'light blue metallic', hex: '#4a90d9' },
  { label: 'Bege', value: 'champagne beige', hex: '#d4c5a9' },
];

export const brandNames = Object.keys(carBrands).sort();